---
# Bashlinux::HTTPS::ACM::SSL Certificate
#
#   Cloudformation template to request an SSL certificate
#   for a subdomain
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: ACM SSL Certificate template

###############################################################################
Parameters:

  CertAuthHostedZoneId:
    Description: The Hosted Zone ID of the FQDN
    Type: String
    MinLength: "1"
    MaxLength: "22"

  Environment:
    Description: Environment this domain name belongs to
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: Can only contain "prod" or "staging".
    
  FQDN:
    Description: The fully qualified domain name for the requested certificate
    Type: String
    MinLength: "1"
    MaxLength: "64"
    Default: bashlinux.staging
    
  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

###############################################################################
Resources:

  # SSL Certificate -----------------------------------------------------------
  SslCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName:
        !Join
        - "."
        - - "*"
          - !Ref FQDN
      DomainValidationOptions:
        - DomainName: !Ref FQDN
          HostedZoneId: !Ref CertAuthHostedZoneId
      ValidationMethod: DNS
      Tags:
      - Key: Name
        Value:
          !Join
          - "."
          - - "wildcard"
            - !Ref FQDN
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:network-visibility
        Value: public
      - Key: bashlinux:can-delete
        Value: "false"

###############################################################################
Outputs:

  SslCertificateARN:
    Description: ARN of the SSL Certificate
    Value: !Ref SslCertificate
    Export:
      Name: !Sub "${AWS::StackName}-arn"

  DomainNames:
    Description: Domain Names registered
    Value:
      !Join
      - ""
      - - "*."
        - !Ref FQDN
