---
# Bashlinux::Grafana::IAM::Account
#
#   Cloudformation template to deploy the IAM credentials and policies
#   for granting access on ECR to the Grafana server
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: Grafana IAM permissions template

###############################################################################
Parameters:

  DevOpsBucketName:
    Description: Name of the s3 bucket where the DevOps assets are retrieved
    Type: String
    MinLength: "8"
    MaxLength: "32"
    ConstraintDescription: Length of the name must be between 8 to 32 characters

  Environment:
    Description: VPC environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: Can only contain "prod" or "staging".

###############################################################################
Resources:

  # IAM permissions and credentials -------------------------------------------
  GrafanaIamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: bashlinux-grafana
      Path: "/bashlinux/"

  GrafanaIamManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy for Grafana to gain access to the Cloudwatch
      ManagedPolicyName: bashlinux-grafana-policy
      Path: "/bashlinux/"
      PolicyDocument:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: !Sub "s3://${DevOpsBucketName}/iam-policies/iam_policy_bashlinux_grafana_cloudwatch.json"
      Groups: [ !Ref GrafanaIamGroup ]

  GrafanaIamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: grafana
      Path: "/serviceaccounts/"
      Groups:
      - !Ref GrafanaIamGroup
      Tags:
      - Key: Name
        Value: grafana
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:network-visibility
        Value: public
      - Key: bashlinux:registry-type
        Value: private
      - Key: bashlinux:can-delete
        Value: "false"

  GrafanaIamAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GrafanaIamUser

###############################################################################
Outputs:

  GrafanaAccessKeyId:
    Value: !Ref GrafanaIamAccessKey
    Description: IAM Access Key ID for Grafana server
  GrafanaSecretAccessKey:
    Value: !GetAtt [GrafanaIamAccessKey, SecretAccessKey]
    Description: IAM Secret Access Key for Grafana server
