---
# Bashlinux::MySQL::RDS SecurityGroup
#
#   Cloudformation template to deploy a security group
#   for an RDS cluster exposing the MySQL port
#   on the public subnet
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: RDS MySQL Security Group template

###############################################################################
Parameters:

  Environment:
    Description: MySQL cluster environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: dev
    AllowedValues: [ "prod", "dev" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "dev".

  EnvVpcId:
    Description: VPC where the MySQL cluster is deployed
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: vpc-
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      VPC ID must begin with a letter and contain only alphanumeric characters.

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

  OrigingSecurityGroupId:
    Description: Security Group ID belonging to the origin
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: sg-
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Security group must begin with a letter and contain only alphanumeric
      characters.

###############################################################################
Resources:

  sgEC2MySQLCluster:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to the MySQL cluster port
      VpcId: !Ref EnvVpcId
      SecurityGroupIngress:
      - IpProtocol: "-1"
        FromPort: "0"
        ToPort: "65535"
        SourceSecurityGroupId: !Ref OrigingSecurityGroupId
      - IpProtocol: tcp
        FromPort: "3306"
        ToPort: "3306"
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: "0"
        ToPort: "65535"
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Sub "bashlinux-${Environment}-mysql"
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:can-delete
        Value: "false"

###############################################################################
Outputs:

  sgEC2MySQLClusterSecurityGroup:
    Description: "SecurityGroup: MySQL port exposed"
    Value: !Ref sgEC2MySQLCluster

  sgEC2MySQLClusterGroupId:
    Description: "SecurityGroup: MySQL port exposed"
    Value: !GetAtt sgEC2MySQLCluster.GroupId
    Export:
      Name: !Sub "${AWS::StackName}-sgEC2MySQLClusterGroupId"
