---
# Bashlinux::MySQL::RDS Subnet Group
#
#   Cloudformation template to deploy an RDS Subnet Group
#   for a MySQL cluster on a private subnet
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: RDS Subnet Group template

###############################################################################
Parameters:

  Environment:
    Description: MySQL cluster environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: dev
    AllowedValues: [ "prod", "dev" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "dev".

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

  RDSPrivateSubnets:
    Description: Private subnets 01A where the cluster is deployed
    Type: List<AWS::EC2::Subnet::Id>
    MinLength: "1"
    MaxLength: "96"

###############################################################################
Resources:

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: MySQLSubnetGroup
      DBSubnetGroupName: !Sub "bashlinux-mysql-${Environment}"
      SubnetIds: !Ref RDSPrivateSubnets
      Tags:
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:can-delete
        Value: "false"
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: Name
        Value: !Sub "bashlinux-mysql-${Environment}"

###############################################################################
Outputs:

  RDSSubnetGroupId:
    Description: "SubnetGroup: RDS MySQL SubnetGroup"
    Value: !Ref RDSSubnetGroup
    Export:
      Name: !Sub "${AWS::StackName}-RDSSubnetGroupId"

