---
# Bashlinux::MySQL::RDS Cluster
#
#   Cloudformation template to deploy an RDS MySQL instance
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: RDS MySQL Cluster template

###############################################################################
Parameters:

  Environment:
    Description: MySQL worker environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: dev
    AllowedValues: [ "prod", "dev" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "dev"

  KmsArn:
    Description: KMS symmetric key to encrypt/decrypt RDS storage
    Type: String
    MinLength: "1"
    MaxLength: "128"
    Default: kms-rds
    AllowedPattern: "[a-zA-Z0-9\\-/:]*"

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

  RDSClusterName:
    Description: Name of the cluster
    Type: String
    MinLength: "2"
    MaxLength: "64"
    Default: "db01"
    AllowedPattern: "[a-zA-Z0-9\\-/:]*"

  RDSMultiAZ:
    Description: Either to deploy with a stand-by or just a standalone instance
    Type: String
    MinLength: "1"
    MaxLength: "16"
    Default: "false"
    AllowedValues:
    - "true"
    - "false"

  RDSMySQLEngineVersion:
    Description: RDS Engine version for MySQL DB
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: "8.0.35"
    AllowedValues:
    - "8.0.34"
    - "8.0.35"
    ConstraintDescription: RDS MySQL must be a valid version.

  RDSMySQLUsername:
    Description: RDS username for MySQL DB
    Type: String
    MinLength: "1"
    MaxLength: "16"
    Default: mysql
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: DB Username must contain at least one letter or number.

  RDSMySQLPassword:
    Description: RDS password for MySQL DB
    Type: String
    MinLength: "8"
    MaxLength: "128"
    NoEcho: "true"
    AllowedPattern: "[a-zA-Z0-9#%-=+]*"
    ConstraintDescription: DB Password must contain at least eight characters.

  RDSInstanceSize:
    Description: RDS instance size for MySQL
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: db.t4g.micro
    AllowedValues:
    - db.t4g.micro
    - db.t4g.small
    - db.t4g.medium
    - db.tg4.large
    - db.m7g.medium
    - db.m7g.large
    - db.m7g.xlarge
    - db.m7g.2xlarge
    ConstraintDescription: >
      RDS instance size must be micro, small, medium, or large of the "db.t4g" type
      or medium, large, xlarge, or 2xlarge of the "db.m7g" type.

  RDSStorageSize:
    Description: RDS instance storage size in GiB
    Type: Number
    MinValue: "5"
    MaxValue: "1024"
    Default: "10"
    ConstraintDescription: MySQL storage size in GiB must be a number.

###############################################################################
Resources:

  RDSMySQLInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref RDSStorageSize
      AllowMajorVersionUpgrade: "false"
      CACertificateIdentifier: "rds-ca-rsa2048-g1"
      CopyTagsToSnapshot: "true"
      DBInstanceClass: !Ref RDSInstanceSize
      DBInstanceIdentifier: !Sub "db01-${Environment}"
      DBSubnetGroupName: !ImportValue
        "Fn::Sub": "mysql-${Environment}-rds-subnet-group-RDSSubnetGroupId"
      DeletionProtection: "true"
      Engine: mysql
      EngineVersion: !Ref RDSMySQLEngineVersion
      MasterUsername: !Ref RDSMySQLUsername
      MasterUserPassword: !Ref RDSMySQLPassword
      MultiAZ: !Ref RDSMultiAZ
      PubliclyAccessible: "false"
      StorageEncrypted: "true"
      StorageType: "gp3"
      KmsKeyId: !Ref KmsArn
      VPCSecurityGroups:
        - !ImportValue
            "Fn::Sub": "mysql-${Environment}-rds-security-group-sgEC2MySQLClusterGroupId"
      Tags:
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-role
        Value: db
      - Key: Name
        Value: !Sub "${RDSClusterName}-${Environment}"

###############################################################################
Outputs:

  RDSMySQLInstanceId:
    Description: "RDS: RDS mysql instance ID"
    Value: !Ref RDSMySQLInstance
