---
# Bashlinux::Mongo::DocumentDB Security Group
#
#   Cloudformation template to deploy an EC2 security group
#   for an DocumentDB cluster exposing the Mongo port
#   on a private subnet
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: DocumentDB Mongo Security Group template

###############################################################################
Parameters:

  Environment:
    Description: Mongo cluster environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "staging".

  EnvVpcId:
    Description: VPC where the Mongo cluster is deployed
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: vpc-
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      VPC ID must begin with a letter and contain only alphanumeric characters.

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

  OrigingSecurityGroupId:
    Description: Security Group ID belonging to the origin
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: sg-
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Security group must begin with a letter and contain only alphanumeric
      characters.

###############################################################################
Resources:

  sgEC2MongoCluster:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to the Mongo cluster port
      VpcId: !Ref EnvVpcId
      SecurityGroupIngress:
      - IpProtocol: "-1"
        FromPort: "0"
        ToPort: "65535"
        SourceSecurityGroupId: !Ref OrigingSecurityGroupId
      - IpProtocol: tcp
        FromPort: "27017"
        ToPort: "27017"
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: "0"
        ToPort: "65535"
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Sub "bashlinux-${Environment}-mongo"
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:can-delete
        Value: "false"

###############################################################################
Outputs:

  EC2MongoClusterSecurityGroup:
    Description: "SecurityGroup: Mongo port exposed"
    Value: !Ref sgEC2MongoCluster

  EC2MongoClusterSecurityGroupId:
    Description: "SecurityGroup: Mongo port exposed"
    Value: !GetAtt sgEC2MongoCluster.GroupId
    Export:
      Name: !Sub "${AWS::StackName}-sgEC2MongoClusterGroupId"
