---
# Bashlinux::Builder::IAM::Account
#
#   Cloudformation template to deploy the IAM credentials and policies
#   for granting access on ECR to the Builder server
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: Builder IAM permissions template

###############################################################################
Parameters:

  DevOpsBucketName:
    Description: Name of the s3 bucket where the DevOps assets are retrieved
    Type: String
    MinLength: "8"
    MaxLength: "32"
    ConstraintDescription: Length of the name must be between 8 to 32 characters

  Environment:
    Description: VPC environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: Can only contain "prod" or "staging".

###############################################################################
Resources:

  # IAM permissions and credentials -------------------------------------------
  BuilderIamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: bashlinux-builder
      Path: "/bashlinux/"

  BuilderIamManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy for Builder to gain access to the ECR 
      ManagedPolicyName: bashlinux-builder-policy
      Path: "/bashlinux/"
      PolicyDocument:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: !Sub "s3://${DevOpsBucketName}/iam-policies/iam_policy_bashlinux_builder_${Environment}.json"
      Groups: [ !Ref BuilderIamGroup ]

  BuilderIamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: builder
      Path: "/serviceaccounts/"
      Groups:
      - !Ref BuilderIamGroup
      Tags:
      - Key: Name
        Value: builder
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:network-visibility
        Value: public
      - Key: bashlinux:registry-type
        Value: private
      - Key: bashlinux:can-delete
        Value: "false"

  BuilderIamAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref BuilderIamUser

###############################################################################
Outputs:

  BuilderAccessKeyId:
    Value: !Ref BuilderIamAccessKey
    Description: IAM Access Key ID for Builder server
  BuilderSecretAccessKey:
    Value: !GetAtt [BuilderIamAccessKey, SecretAccessKey]
    Description: IAM Secret Access Key for Builder server
