---
# CloudFormation::API::S3 Bucket
#
#   Cloudformation template to deploy an S3 bucket for the API ENV vars
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: '2010-09-09'
Description: API S3 Bucket template

###############################################################################
Parameters:

  Environment:
    Description: VPC environment
    Type: String
    MinLength: "4"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: Can only contain "prod" or "staging".

  BucketRole:
    Description: Role name of the bucket
    Type: String
    MinLength: "1"
    MaxLength: "42"
    ConstraintDescription: The role name of the bucket must be a string

  BucketUuid:
    Description: Unique ID to make the s3 bucket less discoverable
    Type: String
    MinLength: "21"
    MaxLength: "21"
    ConstraintDescription: Length of the ID must be exactly 21 characters

  KmsArn:
    Description: KMS symmetric key to enable encryption of images
    Type: String
    MinLength: "1"
    MaxLength: "128"
    Default: arn:aws:kms
    AllowedPattern: "[a-zA-Z0-9\\-/:]*"

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

###############################################################################
Resources:
  S3BucketEnvVars:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: !Ref KmsArn
            BucketKeyEnabled: true
      BucketName: !Sub "bashlinux-api-${BucketRole}-${Environment}-${BucketUuid}"
      Tags:
      - Key: Name
        Value: !Sub "bashlinux-api-${BucketRole}-${Environment}-${BucketUuid}"
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:can-delete
        Value: 'false'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

###############################################################################
Outputs:
        
  S3BucketArn:
    Description: The ARN of the S3 bucket holding the ENV vars file
    Value: !GetAtt S3BucketEnvVars.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketEnvVarsArn"
