---
# Bashlinux::Mongo::DocumentDB Subnet Group
#
#   Cloudformation template to deploy an DocumentDB Subnet Group
#   and a Parameter group for a Mongo cluster on a private subnet
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: DocumentDB Subnet Group template

###############################################################################
Parameters:

  Environment:
    Description: Mongo cluster environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "staging".

  DocumentDBPrivateSubnets:
    Description: Private subnets 01A where the cluster is deployed
    Type: List<AWS::EC2::Subnet::Id>
    MinLength: "1"
    MaxLength: "96"

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: gesvi
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

###############################################################################
Resources:

  DocumentDBSubnetGroup:
    Type: AWS::DocDB::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: MongoSubnetGroup
      DBSubnetGroupName: !Sub "bashlinux-mongo-${Environment}"
      SubnetIds: !Ref DocumentDBPrivateSubnets
      Tags:
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:environment-type
        Value: !Ref Environment
      - Key: bashlinux:can-delete
        Value: "false"
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: Name
        Value: !Sub "bashlinux-mongo-${Environment}"

  DocumentDBParameterGroup:
    Type: "AWS::DocDB::DBClusterParameterGroup"
    Properties:
      Description: !Sub "DocumentDB Parameter group for Bashlinux on ${Environment}"
      Family: "docdb5.0"
      Name: !Sub "bashlinux-${Environment}-docdb50"
      Parameters:
          tls: "disabled"
      Tags:
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:environment-type
        Value: !Ref Environment
      - Key: bashlinux:application-role
        Value: db
      - Key: Name
        Value: !Sub "bashlinux-${Environment}-docdb50"

###############################################################################
Outputs:

  DocumentDBSubnetGroupId:
    Description: "SubnetGroup: DocumentDB Mongo SubnetGroup"
    Value: !Ref DocumentDBSubnetGroup
    Export:
      Name: !Sub "${AWS::StackName}-DocumentDBSubnetGroupId"

  DocumentDBParameterGroupName:
    Description: "ParameterGroup: DocumentDB Mongo ParameterGroup"
    Value: !Ref DocumentDBParameterGroup
    Export:
      Name: !Sub "${AWS::StackName}-DocumentDBParameterGroupName"
