---
# Bashlinux::Mongo::DocumentDB Cluster
#
#   Cloudformation template to deploy a DocumentDB Mongo instance
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: DocumentDB Mongo Cluster template

###############################################################################
Parameters:

  Environment:
    Description: Mongo worker environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "staging".

  DocumentDBClusterName:
    Description: Name of the cluster
    Type: String
    MinLength: "2"
    MaxLength: "64"
    Default: "db01"
    AllowedPattern: "[a-zA-Z0-9\\-/:]*"

  DocumentDBInstanceSize:
    Description: DocumentDB instance size for Mongo
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: db.t4g.medium
    AllowedValues:
    - db.t3.medium
    - db.t4g.medium
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r6g.large
    - db.r6g.xlarge
    - db.r6g.2xlarge
    ConstraintDescription: >
      DocumentDB instance size must be mediumf for "db.t3" and "db.t4g" family classes
      or size large, xlarge, or 2xlarge for the "db.r5" or "db.r6g" family classes

  DocumentDBMongoEngineVersion:
    Description: DocumentDB Engine version for Mongo DB
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: "5.0.0"
    AllowedValues:
    - "5.0.0"
    - "4.0.0"
    - "3.0.0"
    ConstraintDescription: DocumentDB Mongo must be a valid version.

  DocumentDBMongoUsername:
    Description: DocumentDB username for Mongo DB
    Type: String
    MinLength: "1"
    MaxLength: "16"
    Default: mongo
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: DB Username must contain at least one letter or number.

  DocumentDBMongoPassword:
    Description: DocumentDB password for Mongo DB
    Type: String
    MinLength: "8"
    MaxLength: "128"
    NoEcho: "true"
    AllowedPattern: "[a-zA-Z0-9#%-=+]*"
    ConstraintDescription: DB Password must contain at least eight characters.

  KmsArn:
    Description: KMS symmetric key to encrypt/decrypt DocumentDB storage
    Type: String
    MinLength: "1"
    MaxLength: "128"
    Default: kms-documentdb
    AllowedPattern: "[a-zA-Z0-9\\-/:]*"

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

###############################################################################
Resources:

  DocumentDBMongoCluster:
    Type: AWS::DocDB::DBCluster
    Properties: 
      CopyTagsToSnapshot: "true"
      DBClusterIdentifier: !Sub "${DocumentDBClusterName}-${Environment}"
      DBClusterParameterGroupName: !ImportValue
        "Fn::Sub": "mongo-${Environment}-documentdb-subnet-group-DocumentDBParameterGroupName"
      DBSubnetGroupName: !ImportValue
        "Fn::Sub": "mongo-${Environment}-documentdb-subnet-group-DocumentDBSubnetGroupId"
      DeletionProtection: "true"
      EngineVersion: !Ref DocumentDBMongoEngineVersion
      KmsKeyId: !Ref KmsArn
      MasterUsername: !Ref DocumentDBMongoUsername
      MasterUserPassword: !Ref DocumentDBMongoPassword
      Port: "27017"
      StorageEncrypted: true
      StorageType: standard
      VpcSecurityGroupIds:
        - !ImportValue
            "Fn::Sub": "mongo-${Environment}-documentdb-security-group-sgEC2MongoClusterGroupId"
      Tags:
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-role
        Value: db
      - Key: Name
        Value: !Sub "${DocumentDBClusterName}-${Environment}-cluster"

  DocumentDBMongoInstance:
    Type: AWS::DocDB::DBInstance
    DependsOn: DocumentDBMongoCluster
    Properties:
      AutoMinorVersionUpgrade: true
      DBClusterIdentifier: !Ref DocumentDBMongoCluster
      DBInstanceClass: !Ref DocumentDBInstanceSize
      DBInstanceIdentifier: !Sub "${DocumentDBClusterName}-${Environment}"
      Tags:
      - Key: bashlinux:network-visibility
        Value: private
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-role
        Value: db
      - Key: Name
        Value: !Sub "${DocumentDBClusterName}-${Environment}"

###############################################################################
Outputs:

  DocumentDBMongoInstanceId:
    Description: "DocumentDB: DocumentDB mongo instance ID"
    Value: !Ref DocumentDBMongoInstance
